version: '2.0'
services:
  event-agent:
    build: .
    container_name: event-agent
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 127.0.0.1:8000:8000

networks:
  default:
    external:
      name: recipes-network
